### ISSUE TITLE
MRTD Problem Report support

### ISSUE THREAD

**Issue by genaris** [2060-io/2060-service-agent#48]
In order to allow Issuer DTS to tell if an MRTD flow should be canceled because of user refusal.

Service Agent can hook into MrtdProblemReport event or received message and produce an EMrtdDataSubmit/MrzDataSubmit with an error result. However, for that it would need to add a field into these Service Agent submit messages and also have a way to determine if the received problem reports belongs to an Mrz or EMrtd flow. Maybe we should use records in the credo-ts-didcomm-mrtd? Or produce different events/add a field to the event?

**Comment by lotharking** [comment]
I believe it would be worth managing a variable for submissions that can be used across the entire eMRTD or similar message types, similar to the `CredentialState` enum. We could define the initial states as:  
- `Done = "done"`  
- `Declined = "declined"`

**Comment by genaris** [comment]
Developed in #51
